### ISSUE TITLE
Django: Configuration options for SentryCeleryHandler

### ISSUE THREAD

**Issue by andialbrecht** [getsentry/raven-python#1074]
When using a combination of Django and Celery it seems that a Celery handler ist automatically initialized, if the `celery` module could be imported. The Celery handler is initialized in [SentryDjangoHandler.install_celery](https://github.com/getsentry/raven-python/blob/master/raven/contrib/django/models.py#L163) without any options.

It would be nice to have a configuration option for the SentryCeleryHandler, because I'd like to initialize it with `ignore_expected=False`.

**Comment by jamesbeith** [comment]
I just ran into this too. I wanted to add, that it might be worth mentioning on this docs page that if you're using Django then a Celery handler is automatically registered for you. Turns out I've been ending up with two registered Celery handlers and only the one I was can I set `ignore_expected=False `.

https://docs.sentry.io/clients/python/integrations/celery/

**Comment by dhoffman34** [comment]
Just a heads up, we were encountering this same issue. I opened a PR to fix it at https://github.com/getsentry/raven-python/pull/1072

**Comment by andialbrecht** [comment]
This seems to be fixed in the current raven version 6.2.1
